services:
  - type: web
    name: chest-xray-app
    env: docker
    plan: free
    region: singapore
    dockerfilePath: Dockerfile
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8080
